name = "Caddyfile"
grammar = "caddyfile"
path_suffixes = ["Caddyfile", "caddyfile"]
line_comments = ["# "]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = false },
	{ start = "[", end = "]", close = true, newline = false },
	{ start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
tab_size = 4
hard_tabs = true
